server:
  port: 8080

eureka:
  instance:
    hostname: ${HOSTNAME:rally}
    preferIpAddress: ${PREFER_IP:false}
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:registry}:${SERVICE_REGISTRY_PORT:8761}/eureka/

rp:
  mongo:
    host: ${MONGO_HOST:mongodb}
    port: ${MONGO_PORT:27017}
    dbName: reportportal
    user:
    password:

spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:rally}
        prefer-ip-address: false
